python

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,6 +1,9 @@
 #!/bin/bash
+
+
 if [ -z "$PYFILE" ]; then
-echo "Error: PYFILE environment variable not set." >&2
-exit 1
+    echo "Error: PYFILE environment variable not set."
+    exit 1
 fi
+
 python3 "$PYFILE"
